UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';

UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-04-24' WHERE artist = 'Holy Soldier' AND "name" = 'Holy Soldier';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2003' WHERE artist = 'Apocalyptica' AND "name" = 'Reflections Revised';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Behemoth' AND "name" = 'Apostasy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suffocation' AND "name" = 'Effigy of the Forgotten/Pierced from Within Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nile' AND "name" = 'Anihilation of the Wicked';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1984' WHERE artist = 'Discharge' AND "name" = 'Never Again';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1982-03-04' WHERE artist = 'Circle Jerks' AND "name" = 'Wild in the Streets';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1986-11' WHERE artist = 'Dead Kennedys' AND "name" = 'Bedtime for Democracy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995-11-13' WHERE artist = 'Beastie Boys' AND "name" = 'Aglio E Olio';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço Curto... Prazo Longo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço.Curto..Prazo.Longo';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1984-03' WHERE artist = 'Minor Threat' AND "name" = 'First Two Seven Inches';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço curto...Prazo longo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Velvet Underground' AND "name" = 'White Light / White Heat';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dinosaur Jr' AND "name" = 'you''re living all over me';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arsonists Get All The Girls' AND "name" = 'Game Of Life';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-12-26' WHERE artist = 'Bring Me the Horizon' AND "name" = 'Drown (Live from Maida Vale)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1996-06-25' WHERE artist = 'Biohazard' AND "name" = 'Mata Leao';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1997-06-16' WHERE artist = 'Charlie Brown JR.' AND "name" = 'Transpiração Contínua Prolongada';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço Curto... Prazo Longo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço.Curto..Prazo.Longo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rage Against the Machine' AND "name" = 'Rage Against The Machine/Evil Empire';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2007-11-15' WHERE artist = 'Charlie Brown JR.' AND "name" = 'Ritmo, Ritual e Responsa';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-02-02' WHERE artist = 'Lil'' Wayne' AND "name" = 'ReBIRTH';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço curto...Prazo longo';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2021-08-13' WHERE artist = 'Elton John' AND "name" = 'Cold Heart (PNAU Remix)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2016-02-26' WHERE artist = 'Home' AND "name" = 'Falling Into Place';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-11-05' WHERE artist = 'Timecop1983' AND "name" = 'Night Drive';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1990-08-07' WHERE artist = 'Extreme' AND "name" = 'Extreme II - Pornograffitti';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-01-01' WHERE artist = 'Idiot Flesh' AND "name" = 'Tales of Instant Knowledge and Sure Death';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Les Claypool & The Holy Mackerel' AND "name" = 'High Ball with the Devil';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995-11-01' WHERE artist = 'Incubus' AND "name" = 'The Fungus Amongus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Incubus' AND "name" = 'Science';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-04-23' WHERE artist = 'Primus' AND "name" = 'Frizzle Fry (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002' WHERE artist = 'James Taylor Quartet' AND "name" = 'Room At The Top';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Incubus' AND "name" = 'The Fungus Amongus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Extreme' AND "name" = 'Extreme II - Pornograffitti';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonsorrow' AND "name" = 'Havitetty';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Opeth' AND "name" = 'My Arms Your Hearse';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'November''s Doom' AND "name" = 'Into Night''s Requiem Infernal';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-05-26' WHERE artist = 'Gojira' AND "name" = 'Silvera';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sikth' AND "name" = 'The Trees Are Dead & Dried Out... Wait for Something Wild';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Chariot' AND "name" = 'Unsung';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dillinger Escape Plan' AND "name" = 'Plagiarism - EP';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-04-24' WHERE artist = 'War from a Harlots Mouth' AND "name" = 'In Shoals';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'Greatest Lovesongs, Vol. 666';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 5: Right Here in My Arms)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Uneasy Listening Vol.1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Deep Shadows & Brilliant Highlights';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 9: In Joy and Sorrow)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Unplugged and More';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Alternative Collection';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Alternative Collection';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Love Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Greatest lovesongs vol.666';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'And Love Said No';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Uneasy Listening Vol.2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2003.04.14 - Love Metal [Limited Edition]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Live & Undercover';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 4: Join Me)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Razorblade Romance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 3: When Love and Death Embrace)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2004-05-29: Landgraaf, The Netherlands';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006-10-27' WHERE artist = 'Him' AND "name" = 'Uneasy Listening Vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Venus Doom';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-02-08' WHERE artist = 'Him' AND "name" = 'Screamworks: Love In Theory And Practice';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Screamworks: Love In Theory And Practice, Chapters 1-13';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002' WHERE artist = 'Various Artists' AND "name" = 'Love Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'Razorblade Romance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'Deep Shadows and Brilliant Highlights';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Greatest Love Songs Vol. 666';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Uneasy Listening, Vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'And Love Said No: Greatest Hits 1997-2004 [Germany]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Tears On Tape (BONUS)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2017-03-01' WHERE artist = 'Flover' AND "name" = 'Dark & Sweet';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amon Amarth' AND "name" = 'Thor Arise';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Ultra Rare Trax, Volume 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mithotyn' AND "name" = 'King Of A Distant Forest';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1998-01-21' WHERE artist = 'Falkenbach' AND "name" = '...Magni Blandinn Ok Megintiri...';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Exciter' AND "name" = 'Violence And Force';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suffocation' AND "name" = 'Effigy of the Forgotten/Pierced from Within Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Paris Hilton' AND "name" = '[non-album tracks]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Disfiguring the Goddess' AND "name" = 'Disfiguring The Goddess';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-06-26' WHERE artist = 'G-Eazy' AND "name" = 'Everything''s Strange Here';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-06-26' WHERE artist = 'G-Eazy' AND "name" = 'Everything's Strange Here';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pelican' AND "name" = 'Fire in Our Throats Will Beckon the Thaw, The';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Shels' AND "name" = 'Sea of the Dying Dhow';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-05-25' WHERE artist = 'The Devil Wears Prada' AND "name" = 'Sour Breath';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rosetta' AND "name" = 'The Galilean Satellites';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2017-10-20' WHERE artist = 'Amenra' AND "name" = 'Mass VI';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rosetta' AND "name" = 'Wake / Lift';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1991-08-16' WHERE artist = 'Melvins' AND "name" = 'Eggnog';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2020-09-25' WHERE artist = 'The Ocean' AND "name" = 'Phanerozoic II: Mesozoic | Cenozoic';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-05-11' WHERE artist = 'The Body' AND "name" = 'I Have Fought Against It, But I Can’t Any Longer.';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-05-24' WHERE artist = 'Boris' AND "name" = 'Heavy Rocks (2011)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Orange Goblin' AND "name" = 'Time Traveling Blues';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-07-13' WHERE artist = 'Obscura' AND "name" = 'Diluvium';
UPDATE "public"."Album" SET "numberOfTracks" = 31, "date" = '2001' WHERE artist = 'Excrementory Grindfuckers' AND "name" = 'Guts, Gore and Grind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Grand Belial's Key' AND "name" = 'Mocking The Philantropist';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Residents' AND "name" = 'Third Reich 'n' Roll';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-12-11' WHERE artist = 'Chelsea Grin' AND "name" = 'Skin Deep';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2007-10-05' WHERE artist = 'Postmortem Promises' AND "name" = 'Postmortem Promises';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2010-03-15' WHERE artist = 'Ease of Disgust' AND "name" = 'Constructed';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-06-26' WHERE artist = 'Dysphoria' AND "name" = 'Satyriasis XXI';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-06-01' WHERE artist = 'Acranius' AND "name" = 'The Echo Of Her Cracking Chest';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2012-09-15' WHERE artist = 'Angelmaker' AND "name" = 'Decay';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1992-06-05' WHERE artist = 'Impetigo' AND "name" = 'Horror of the Zombies';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1998' WHERE artist = 'Cock and Ball Torture' AND "name" = 'Cocktales';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Last Days of Humanity' AND "name" = 'The Sounds of Rancid Juices Sloshing Around Your Coffin';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2000-06-23' WHERE artist = 'Cock and Ball Torture' AND "name" = 'Opus(sy) VI';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-06-07' WHERE artist = 'Disgorge' AND "name" = 'Forensick';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-02-01' WHERE artist = 'Disgorge' AND "name" = 'Necrholocaust';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008-10-01' WHERE artist = 'Gronibard' AND "name" = 'We are french, fukk you';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-10-11' WHERE artist = 'TesseracT' AND "name" = 'Concealing Fate (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-05-11' WHERE artist = 'Voyager' AND "name" = 'Ghost Mile';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2010-11-05' WHERE artist = 'Behemoth' AND "name" = 'Evangelia Heretika';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1998-11-23' WHERE artist = 'Korn' AND "name" = 'Got the Life';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1999-02-25' WHERE artist = 'Korn' AND "name" = 'Freak on a Leash';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2007-06-12' WHERE artist = 'Korn' AND "name" = 'Evolution';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-08-27' WHERE artist = 'Raga Rockers' AND "name" = 'Ûbermensch';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-04-15' WHERE artist = 'БеZумные Усилия' AND "name" = 'Огни Неизвестности';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-05-27' WHERE artist = 'Kandia' AND "name" = 'All Is Gone';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2011-05-06' WHERE artist = 'Architects' AND "name" = 'Heartburn - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2012-08-14' WHERE artist = 'The Afterimage' AND "name" = 'Formless';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2020-03-13' WHERE artist = 'Invent, Animate' AND "name" = 'Greyview';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avantasia' AND "name" = 'The Metal Opera Pt. II';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-11-09' WHERE artist = 'Carnival in Coal' AND "name" = 'French Cancan';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Unexpect' AND "name" = '_We, Invaders';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-03-28' WHERE artist = 'Pin-Up Went Down' AND "name" = '2Unlimited';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-11-24' WHERE artist = 'Solefald' AND "name" = 'Black for Death - An Icelandic Odyssey part II';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2012-03-03' WHERE artist = 'Emmure' AND "name" = 'I Am Onslaught / Protoman';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2016-12-16' WHERE artist = 'Emmure' AND "name" = 'Russian Hotel Aftermath / Torch';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-12-19' WHERE artist = '8CONTROL' AND "name" = 'You Should Have Cared';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-01-10' WHERE artist = 'Cold Hard Truth' AND "name" = 'Deliver the Fear';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-09-28' WHERE artist = 'Stand United' AND "name" = 'Adherence';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-05-30' WHERE artist = 'Slam Coke' AND "name" = 'First Cookie: Fick Die Bude Kaputt';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-04-04' WHERE artist = 'Breakdown of Sanity' AND "name" = 'MIRRORS';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2012-05-22' WHERE artist = 'Obey the Brave' AND "name" = 'Ups & Downs';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2013-02-28' WHERE artist = 'Nasty' AND "name" = 'Love';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-09-09' WHERE artist = 'Nasty' AND "name" = 'Liebe';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-01-01' WHERE artist = 'Breakdown of Sanity' AND "name" = 'My Heart in Your Hands (Re-Recorded)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009' WHERE artist = 'Magilum' AND "name" = 'Kirmizi Kar';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2012-11-23' WHERE artist = 'Antimatter' AND "name" = 'Fear of a Unique Identity';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2019-02-01' WHERE artist = 'bruit noir' AND "name" = 'II / III';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007' WHERE artist = 'Sopor' AND "name" = 'Sleep Inside 2007';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-11-16' WHERE artist = 'Karg' AND "name" = 'Dornenvögel';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1992' WHERE artist = 'Assück' AND "name" = 'Blindspot';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lock Up' AND "name" = 'Pleasure Paves Sewers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nails' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-08-07' WHERE artist = 'Cattle Decapitation' AND "name" = 'The Anthropocene Extinction';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2018-07-06' WHERE artist = 'Xavlegbmaofffassssitimiwoamndutroabcwapwaeiippohfffx' AND "name" = 'Gore 2.0';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2020-03-29' WHERE artist = 'Sadness' AND "name" = 'Alluring the distant eye';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2021-11-05' WHERE artist = 'møl' AND "name" = 'Diorama';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2021-10-29' WHERE artist = 'Ghost Bath' AND "name" = 'Self Loather';